### ISSUE TITLE
Alternative separators

### ISSUE THREAD

**Issue by BeauAgst** [irodger/price-like-humans#1]
I see that using `getPrice()` we can change separators for the decimal point, but it would also be nice to format the other separators. So instead of:

```
priceLikeHumans.getPrice(12345.6789, ',') 
//> "12 345,678 9"
```

We could do something like
```
priceLikeHumans.getPrice(12345.6789, '.', ',') 
//> "12,345.6789"
```

Some different number formats can be found [here](https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html) 

Love your project! 💯

**Comment by irodger** [comment]
Thank you for your feedback. This is added just now in v0.2.3.

Have a good day!
